use asamza;

INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('1', 'CAPITAL');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('2', 'GENERAL ALVEAR');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('3', 'SAN MARTIN');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('4', 'GODOY CRUZ');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('5', 'GUAYMALLEN');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('6', 'JUNIN');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('7', 'LA PAZ');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('8', 'LAS HERAS');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('9', 'LAVALLE');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('10', 'LUJAN');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('11', 'MAIPU');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('12', 'MALARGUE');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('13', 'RIVADAVIA');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('14', 'SAN CARLOS');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('15', 'SAN RAFAEL');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('16', 'SANTA ROSA');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('17', 'TUNUYAN');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('18', 'TUPUNGATO');
INSERT INTO `asamza`.`munis` (`id`, `name`) VALUES ('19', 'DALVIAN');